### ISSUE TITLE
Template doesn't run in Xcode 12.0

### ISSUE THREAD

**Issue by BryanJBryce** [icerockdev/moko-template#16]
Template doesn't run in Xcode 12.0

**Comment by menjoo** [comment]
Hi,

I think I have the same trouble getting the iOS app to run. After pulling the sources. I did `pod install`:
```
menno@MBP-van-Menno ios-app % pod install
Analyzing dependencies
Downloading dependencies
prepare MultiPlatformLibrary.framework (require some time...)
preparing MultiPlatformLibrary.framework complete
Generating Pods project
Integrating client project
Pod installation complete! There are 5 dependencies from the Podfile and 6 total pods installed.

[!] Your project does not explicitly specify the CocoaPods master specs repo. Since CDN is now used as the default, you may safely remove it from your repos directory via `pod repo remove master`. To suppress this warning please add `warn_for_unused_master_specs_repo => false` to your Podfile.
menno@MBP-van-Menno ios-app % 
```

Also building the project goes well:
```
menno@MBP-van-Menno moko-mvvm-app % ./gradlew build

...

BUILD SUCCESSFUL in 6s
344 actionable tasks: 12 executed, 332 up-to-date
menno@MBP-van-Menno moko-mvvm-app % 

```

After this Android app runs well, but iOS I can't get it to run. If I start it from Android Studio the simulator starts but nothing happens. Also no error in the build log:
<img width="1535" alt="Screenshot 2020-10-29 at 13 19 30" src="https://user-images.githubusercontent.com/3490488/97573026-6bb48880-19e9-11eb-8cf5-a4e0af9649a0.png">

When trying to build it from Xcode, the build fails saying `No such module 'MultiPlatformLibraryUnits'`:
![Screenshot 2020-10-29 at 13 20 42](https://user-images.githubusercontent.com/3490488/97573121-91419200-19e9-11eb-9368-993994190b6e.png)

Any ideas what to try?

**Comment by rhonyabdullah** [comment]
Same, i also facing this issue

**Comment by Alex009** [comment]
hi! try set build only active architecture
![image](https://user-images.githubusercontent.com/5010169/100750668-f3424c80-3418-11eb-9444-caf43f07ef78.png)
in [this branch](https://github.com/icerockdev/moko-template/compare/sqldelight) i do it and also run 
```
pod deintegrate
pod install
```
to reintegrate pods with new version
