### ISSUE TITLE
Problem with moko resources in the template

### ISSUE THREAD

**Issue by Jaime97** [icerockdev/moko-template#18]
Hello,

I'm trying to use Moko-resources within this template. I know the library is already included in the project, so I created a `string.xml` and I can access it from the **android-app** module. However, I'm also trying to use the strings from the **feature** module, in one of the `ViewModels`, using the example function:

```
fun getMyString(): StringDesc {
        return StringDesc.Resource(MR.strings.my_string)
    }
```

The problem is that the class `MR` can't be found from this scope, and I don't know how to solve it. I've already generated the class with the gradle task  `generateMRcommonMain`, and I can see it within `build/generated/moko/commonMain/src/bundleid/`.

Can anyone help me solve it?

**Comment by Alex009** [comment]
hello!
if you want use strings from feature module you should move strings resources into feature module (and configure moko-resources plugin in feature module too)

**Comment by Jaime97** [comment]
Thanks Aleksey! I've seen now that you're injecting a ListViewModel.String into you ViewModel from the SharedFactory, and that make it easier and cleaner than using the MR directly in feature module, so I have done it that way.
