### ISSUE TITLE
Questions: IosArm64 Actual declaration shortcut keep complaining.

### ISSUE THREAD

**Issue by rhonyabdullah** [icerockdev/moko-template#22]
Hello @Alex009 
As discussed [here Adding SQLDelight to the project ](https://github.com/icerockdev/moko-template/issues/19#issuecomment-736593789) i try to move out my [DatabaseDriverFactory](https://github.com/rhonyabdullah/OWeatherKMM/blob/424c14c33cf7d2f733d2598e22afffe34314bc09/shared/src/commonMain/kotlin/com/rnd/oweatherkmm/data/source/cache/DatabaseDriverFactory.kt#L10) class into iosX64Main folder, but after rebuilding the project i didn't see any iosArm64Main shortcut generated like moko-template did [here](https://github.com/icerockdev/moko-template/issues/19#issuecomment-736583122)
I am also upgrade kotlin version to 1.4.21 and moko-mvvm to 0.8.1 as described on moko-mvvm [readme file](https://github.com/icerockdev/moko-mvvm#versions)
My question is:
1. How my project can be able to generate that iosArm64Main shortcut folder automatically like moko-template do ?
2. Also, my [serializable](https://github.com/rhonyabdullah/OWeatherKMM/blob/7795a6944264c2bc6ca6a47650afbc091ae2b850/shared/src/commonMain/kotlin/com/rnd/oweatherkmm/domain/entity/Greeting.kt#L5) annotation is missing each time "build" project executed, but if i try to put serializable annotation alongside moko-template [News.kt entity class](https://github.com/icerockdev/moko-template/blob/0edde07132bd36e0b5e857ceadc5c02f486c0568/mpp-library/domain/src/commonMain/kotlin/org/example/library/domain/entity/News.kt#L11) it's just fine. 

![](https://i.ibb.co/MVX8Sv8/Screen-Shot-2021-01-04-at-12-42-02-PM.png)

**Comment by Alex009** [comment]
hi!
1. `iosArm64Main` in [issue](https://github.com/icerockdev/moko-template/issues/19#issuecomment-736583122) is just symbolic link. to create it use `ln -s iosX64Main iosArm64Main`. nothing is done automatically.
2. in samples your class marked as @Serializable, but in template used @Parcelize - it's two different annotations for different purpose. Parcelize is from https://github.com/icerockdev/moko-parcelize to support [android Parcelable generation](https://developer.android.com/kotlin/parcelize). Serializable is from https://github.com/Kotlin/kotlinx.serialization to serialize to/from Json.

**Comment by rhonyabdullah** [comment]
> hi!
> 
> 1. `iosArm64Main` in [issue](https://github.com/icerockdev/moko-template/issues/19#issuecomment-736583122) is just symbolic link. to create it use `ln -s iosX64Main iosArm64Main`. nothing is done automatically.
> 2. in samples your class marked as @serializable, but in template used @Parcelize - it's two different annotations for different purpose. Parcelize is from https://github.com/icerockdev/moko-parcelize to support [android Parcelable generation](https://developer.android.com/kotlin/parcelize). Serializable is from https://github.com/Kotlin/kotlinx.serialization to serialize to/from Json.

1.  I have done, now it's working, thank you.
2. I understand that between serializable & moko parcelize is two different, but strange is coming if i try to replace parcelize or put serializable alongside [News.kt](https://github.com/icerockdev/moko-template/blob/0edde07132bd36e0b5e857ceadc5c02f486c0568/mpp-library/domain/src/commonMain/kotlin/org/example/library/domain/entity/News.kt) class it is still working fine, this issue also appear on kmm sample project and i was create a new issue [there](https://github.com/kotlin-hands-on/kmm-networking-and-data-storage/issues/9), hope they can explain and help how to resolve.

![](https://i.ibb.co/LzsTvL9/Screen-Shot-2021-01-04-at-3-05-20-PM.png)

**Comment by rhonyabdullah** [comment]
I think i can close this issue because error is now heading to kotlinx serialization.
