### ISSUE TITLE
I'm getting this issue when I try to run my iOS app in Xcode 11.3.1 "Compiling for iOS 9.0, but module 'AlamofireImage' has a minimum deployment target of iOS 10.0" . can anyone help me to resolve this error. need quick reply.

### ISSUE THREAD

**Issue by gayathriidss** [icerockdev/moko-template#23]

**Comment by Alex009** [comment]
Use last moko-mvvm version or just add in podfile alamofireimage 3.5.2 version

**Comment by gayathriidss** [comment]
> Use last moko-mvvm version or just add in podfile alamofireimage 3.5.2 version

Once I changed the mono-mvvm latest version as 0.8.1 or using pod alamofireimage 3.5.2 also I'm getting like this error "No such module 'MultiPlatformLibrary'" even though the library is present in my code

**Comment by Alex009** [comment]
@gayathriidss if you got `no such module` maybe multiplatform module not compiled successfully to iOS framework before `pod install` call. 
try call it:
```
./gradlew syncMultiPlatformLibraryDebugFrameworkIosX64
(cd ios-app && pod install)
./ios-app/ios-app.xcworkspace
```
