### ISSUE TITLE
Generating multiple APIs on the domain module

### ISSUE THREAD

**Issue by michaelbrainvu** [icerockdev/moko-template#5]
I tried to generating another api on the domain module by adding another openApiGenerate section to the build script but it seems that the generator generates only the last API entry. Is there a way generate several APIs? Do I need to create a separate domain module for each API?

**Comment by Alex009** [comment]
try setup by this guide https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-gradle-plugin#generate-multiple-sources

but necessary is `generatorName.set("kotlin-ktor-client")`

**Comment by michaelbrainvu** [comment]
Trying to do something like:
tasks.register<org.openapitools.generator.gradle.plugin.tasks.GenerateTask>("generateOpenApi") {
    inputSpec.set(file("src/openapi.yml").path)
    apiPackage.set("dev.icerock.moko.network.generated.apis")
    generatorName.set("kotlin-ktor-client")
}

But always get an error: language/generatorName must be specified
Not sure what I am doing wrong
In any case, looking at the moko network plugin code, it seems that the plugin deletes all output generated code before generating new code so I do not see how I can generate several apis on one module. It seems that each API must be located on its own module

**Comment by Alex009** [comment]
I agree, at the moment it is not possible to make several APIs in one module.

You can add issue to https://github.com/icerockdev/moko-network with suggestion of support multiple API

**Comment by Alex009** [comment]
in moko-network 0.9.0 available multiple api generation - https://github.com/icerockdev/moko-network/releases/tag/release%2F0.9.0
